export const contentList = [
  {
    id: 'ct-1',
    containerTitle: '지금, 화제의 그 작품',
    content: [
      {
        id: 1,
        title: '돈만 주시면 시키시는 거 다 합니다',
        author: '봉봉구리',
        score: 4.7,
        review: 9343,
      },
      {
        id: 2,
        title: '시한부라서 대충 살겠습니다',
        author: '은방울꽃',
        score: 4.7,
        review: 8942,
      },
      {
        id: 3,
        title: '철물점 막내아들',
        author: '박카스',
        score: 4.7,
        review: 2526,
      },
      {
        id: 4,
        title: '다 잘 될 거에요',
        author: '행복한구름',
        score: 4.7,
        review: 3257,
      },
      {
        id: 5,
        title: '자고 일어나니 백수가 된 건에 대하여',
        author: '개백수박수',
        score: 4.6,
        review: 1124,
      },
      {
        id: 6,
        title: '그 개발자가 사는 법',
        author: '주니어갭알자',
        score: 4.5,
        review: 7351,
      },
    ],
  },
  {
    id: 'ct-2',
    containerTitle: '회·빙·환이 대세~',
    content: [
      {
        id: 7,
        title: '지겨운 회·빙·환은 가라',
        author: '초록새',
        score: 4.3,
        review: 932,
      },
      {
        id: 8,
        title: '대공님, 이혼해주세요',
        author: '율리아',
        score: 4.0,
        review: 8942,
      },
      {
        id: 9,
        title: '이세계로 넘어와 대공녀가 되었다',
        author: '하하히히',
        score: 4.0,
        review: 2526,
      },
      {
        id: 10,
        title: '서브남주를 지켜보겠습니다',
        author: '이리야',
        score: 4.4,
        review: 3257,
      },
      {
        id: 11,
        title: '사업 천재 빌런 3세',
        author: '금은보화',
        score: 4.3,
        review: 1124,
      },
      {
        id: 12,
        title: '흑막가의 사랑받는 막내 딸',
        author: '이빌런',
        score: 4.2,
        review: 7351,
      },
    ],
  },
  {
    id: 'ct-3',
    containerTitle: '조회수 많은 에세이',
    content: [
      {
        id: 13,
        title: '구직을 합니다',
        author: '봉원희',
        score: 4.1,
        review: 133,
      },
      {
        id: 14,
        title: '떡볶이가 먹고 싶은 이유',
        author: '이해',
        score: 4.8,
        review: 1241,
      },
      {
        id: 15,
        title: '건강한 몸을 가지는 법',
        author: '홍길동',
        score: 4.2,
        review: 36,
      },
      {
        id: 4,
        title: '다 잘 될 거에요',
        author: '행복한구름',
        score: 4.7,
        review: 3257,
      },
      {
        id: 16,
        title: '꼭 알아야하는 경제 상식',
        author: '김경제',
        score: 4.1,
        review: 111,
      },
      {
        id: 17,
        title: '천재 개발자가 되고 싶으신가요?',
        author: '나천재',
        score: 3.9,
        review: 731,
      },
    ],
  },
];
